name = "MyExample"
uuid = "2add3620-b4ab-40ad-8cdf-11046e16dc34"
authors = ["Greg Alspaugh"]
version = "0.1.0"

[deps]
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
